### ISSUE TITLE
[bug] 'typecho.typecho_email' does not exist.

### ISSUE THREAD

**Issue by JJJYmmm** [soxft/CommentToMail#11]
### Environment

- typecho 1.2.0
- PHP 8.0
- Nginx 1.20.2
- MariaDB 10.5.15

### Issue

发送邮件时提示typecho.typecho_email这张表不存在，看了一下Plugin.php中的dbInstall
https://github.com/soxft/CommentToMail/blob/07c5df194d2bc817ed7ecfb9bfe773135b18a62a/Plugin.php#L245-L251

发现是type字段的问题，我这里返回的type是mysqli而不是mysql

### Solution

复制一份/sql下的Mysql.sql，重命名为Mysqli.sql

**Comment by soxft** [comment]
好家伙，怎么变成 mysqli 了, 去改一下，感谢
