### ISSUE TITLE
Error: Undefined constant "TypechoPlugin\CommentToMail\GLOB_BRACE" in /app/usr/plugins/CommentToMail/Console.php:49

### ISSUE THREAD

**Issue by buzhangjiuzhou** [soxft/CommentToMail#3]
安装，启用，配置都没有问题，但是一评论就报错。

在评论邮件提醒中看到了这个报错。

Error: Undefined constant "TypechoPlugin\CommentToMail\GLOB_BRACE" in /app/usr/plugins/CommentToMail/Console.php:49
Stack trace:
#0 /app/var/Typecho/Widget.php(155): TypechoPlugin\CommentToMail\Console->execute()
#1 /app/usr/plugins/CommentToMail/page/console.php(54): Typecho\Widget::widget('TypechoPlugin\\C...')
#2 /app/admin/extending.php(14): require_once('/app/usr/plugin...')
#3 {main}

在StackOverflow中看到了解释，我用的是dockers alpine镜像导致了报错。

https://stackoverflow.com/questions/48377176/notice-use-of-undefined-constant-glob-brace

**Comment by buzhangjiuzhou** [comment]
https://github.com/idawnlight/CommentToMail/commit/55dfa20e62c67a984d4fa7a7ea54c9bc824a4a45

这里是解决方案。

**Comment by soxft** [comment]
好的, 感谢
