### ISSUE TITLE
评论之后没有邮件

### ISSUE THREAD

**Issue by buzhangjiuzhou** [soxft/CommentToMail#4]
最外部的系统是Ubuntu 20.04
里面装了docker，使用的joyqi/typecho:1.2.0-php8.0-fpm-alpine镜像。

安装之后一开始报错，发现是PHP8.0的问题，然后自己手动改了代码：
之前        $files = glob($this->_template_dir . '*.{html,HTML}', GLOB_BRACE);
之后        $files = glob($this->_template_dir . '*.html');

后来发现还是不能用，于是自己手动添加了postgres的一个文件内容如下：

CREATE TABLE IF NOT EXISTS typecho_mail (
  id SERIAL PRIMARY KEY,
  content text NOT NULL,
  sent int DEFAULT 0
);

然后没有出现任何报错了，同时测试邮件可以发出去，但是评论之后没有邮件。

我用输出log的方式调试了一下，发现Plugin.php里面的函数都可以正常执行，但是Action.php中的函数没有一个得到了执行。看typecho的官方文档也没有提到Action的作用，我也不明白这个文件中的函数是怎么被调用的，所以过来求助。

**Comment by soxft** [comment]
今天也有一位用户 提到了这个问题, 可以看下 #3  这个

glob貌似是用来查找文件的吧, 这个不太清楚, 我自己测试 在 非docker环境下 使用php8是可以正常使用的

action 类似是 typecho 的 一个路由, 在Plugin.php 中注册后 可以直接请求 https://example.com/action/aaaa

**Comment by soxft** [comment]
查了一下 应该是 GLOB_BRACE  在某些操作系统中 是不能使用的
已经根据 #3  的建议改了下main分支

**Comment by soxft** [comment]
对了 那个 mailLog 的函数 是原先插件中, 可以设置发送后记录日志. 但是 我认为没什么用就移除了, 那个函数 忘记删了 不好意思

**Comment by buzhangjiuzhou** [comment]
> 对了 那个 mailLog 的函数 是原先插件中, 可以设置发送后记录日志. 但是 我认为没什么用就移除了, 那个函数 忘记删了 不好意思

我在调试的时候又把它加回来了，哈哈哈

**Comment by soxft** [comment]
> > 对了 那个 mailLog 的函数 是原先插件中, 可以设置发送后记录日志. 但是 我认为没什么用就移除了, 那个函数 忘记删了 不好意思
> 
> 我在调试的时候又把它加回来了，哈哈哈

啊 我看了下你的分支, 弄混淆了😂

**Comment by soxft** [comment]
你可以直接在 sendMail 函数里调用 mailLog

**Comment by soxft** [comment]
typecho 的文档的确不全, 改的时候挺费劲

**Comment by buzhangjiuzhou** [comment]
> action 类似是 typecho 的 一个路由, 在Plugin.php 中注册后 可以直接请求 https://example.com/action/aaaa

我刚刚请求了一下我这里的链接，发现log有输出了。也就是说，很可能Action.php是正常的。不过有报错就是好情况，至少我知道怎么调试。

但是还需要解决的问题是我正常评论为什么没有发出去这个链接。

**Comment by soxft** [comment]
得定时访问 https://blog.example.com/action/comment-to-mail?do=deliverMail&key={KEY}
在插件设置底部可以看到

报错的话, config.ini.php 中 可以设置  `define('__TYPECHO_DEBUG__', true);` 来开启debug 查看详细错误

**Comment by buzhangjiuzhou** [comment]
> 得定时访问 [https://blog.example.com/action/comment-to-mail?do=deliverMail&key={KEY}](https://blog.example.com/action/comment-to-mail?do=deliverMail&key=%7BKEY%7D) 在插件设置底部可以看到
> 
> 报错的话, config.ini.php 中 可以设置 `define('__TYPECHO_DEBUG__', true);` 来开启debug 查看详细错误

？意思是需要我定期访问这个链接邮件才能发出去吗？我还以为是设置好了，它就可以自动检测到有评论，然后发送邮件。我之前用的LoveKKComment就是这样的，但是好久没更新了，在我更新typecho之后就不能用了。

**Comment by soxft** [comment]
对的, LoveKKComment应该是同步发送吧, 会影响评论速度
这个采用的是异步推送, 对访客体验好点

**Comment by buzhangjiuzhou** [comment]
> 对的, LoveKKComment应该是同步发送吧, 会影响评论速度 这个采用的是异步推送, 对访客体验好点

这样啊，我先把这个异步的调通之后再看看是否要改成同步的，我比较喜欢同步式的，就像GitHub这个评论一样。

**Comment by soxft** [comment]
> > 对的, LoveKKComment应该是同步发送吧, 会影响评论速度 这个采用的是异步推送, 对访客体验好点
> 
> 
> 
> 这样啊，我先把这个异步的调通之后再看看是否要改成同步的，我比较喜欢同步式的，就像GitHub这个评论一样。

嗯嗯

**Comment by buzhangjiuzhou** [comment]
> > > 对的, LoveKKComment应该是同步发送吧, 会影响评论速度 这个采用的是异步推送, 对访客体验好点
> > 
> > 
> > 这样啊，我先把这个异步的调通之后再看看是否要改成同步的，我比较喜欢同步式的，就像GitHub这个评论一样。
> 
> 嗯嗯

感谢！我大概搞清楚了调试的思路了！

**Comment by buzhangjiuzhou** [comment]
Action.php第204行，$this->_cfg->status 是NULL怎么解决？可以跳过吗？还是前面的设置有问题？

![image](https://user-images.githubusercontent.com/19666246/161385500-23135c08-2c93-4546-8c2c-7e15dad098d1.png)

**Comment by soxft** [comment]
这个status 貌似是后台的 

<img width="489" alt="image" src="https://user-images.githubusercontent.com/42080379/161385675-de0d6e59-cd75-4396-874d-31399ec49045.png">

这个设置, 理论上不应该为空啊, 可以用双问号来指定当status为空时的值

**Comment by buzhangjiuzhou** [comment]
> 这个status 貌似是后台的
> 
> <img alt="image" width="489" src="https://user-images.githubusercontent.com/42080379/161385675-de0d6e59-cd75-4396-874d-31399ec49045.png">
> 
> 这个设置, 理论上不应该为空啊, 可以用双问号来指定当status为空时的值

是我的问题，我以为这里的设置是比如有人发了评论，我给他通过之后发邮件提醒他，看了你的回复我发现这里其实是决定那一类邮件要发，我勾选了第一个之后就成功收到了邮件。
![image](https://user-images.githubusercontent.com/19666246/161385827-194f26d5-bd38-44b5-8fe8-3802300547b6.png)

感谢你的帮助，我一会儿整理一下代码，然后派PR。

**Comment by soxft** [comment]
这个, 我个人还是觉得 异步的话体验比较好，  同步的话就新增一个分支吧

**Comment by buzhangjiuzhou** [comment]
> 这个, 我个人还是觉得 异步的话体验比较好， 同步的话就新增一个分支吧

好的！

**Comment by soxft** [comment]
我感觉你博客文章写的很好 ！😂

**Comment by buzhangjiuzhou** [comment]
> 我感觉你博客文章写的很好 ！😂

哈哈哈哈哈，过奖过奖，我还一直想着别人会不会觉得我无病呻吟，不过考虑到我博客没几个人看，就淡定了。
