### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Glanwu** [soxft/CommentToMail#7]
如下错误是需要使用PHP8.0么，因为现在是PHP7.2。如果是PHP7.2，应该如何修改，谢谢

`syntax error, unexpected 'Db' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)`

**Comment by soxft** [comment]
插件使用了 php8的特性, 仅支持php8 与 typecho 1.2.0,

不支持7x
