### ISSUE TITLE
启用后控制台有多个相同内容的标签

### ISSUE THREAD

**Issue by tamakyi** [soxft/CommentToMail#9]
![IMG_20220714_083411](https://user-images.githubusercontent.com/25850853/178859863-6aef488f-6500-4b2d-9990-81d8763501b0.jpg)
控制台有多个相同内容的标签。
环境typecho1.2+php8.0，启用后在后台的控制台如图所示。

**Comment by soxft** [comment]
插件卸载的时候 不能直接删除文件， 需要在控制台点击禁用
也有可能是 启用的时候 点了多次？？
不太清楚，我使用时没有遇到类似的问题

**Comment by tamakyi** [comment]
> 

好 我自己调试看看

**Comment by soxft** [comment]
嗯嗯
